### ISSUE TITLE
Add: Event Listener For Various Properties

### ISSUE THREAD

**Issue by Readtt** [Piotrekol/ProcessMemoryDataFinder#15]
Title says it all.

**Comment by Piotrekol** [comment]
The title says nothing, elaborate more.

**Comment by Readtt** [comment]
An example could be an OnMiss function, it gets called everytime the ReadHitMiss function increments by 1 (user misses). Another example could also be OnBeatmapChange, it gets called everytime the current beatmap doesn't equal to the previous beatmap (beatmap changed).

**Comment by Piotrekol** [comment]
That should be implemented by implementing application/library(see [StreamCompanion OsuMemoryEventSource plugin code](https://github.com/Piotrekol/StreamCompanion/tree/master/plugins/OsuMemoryEventSource)). OsuMemoryDataProvider by itself never does any memory reads unless asked to, since there is overhead with each memory read.

This would result in about 70(quick count) OnX events being created in addition to required conditional reading logic.. with is plain ridiculous. I'm almost certain this will never happen.

**Comment by Readtt** [comment]
Alright.
